### ISSUE TITLE
Launching kinect_calibrator, nothing's happening

### ISSUE THREAD

**Issue by Xonxt** [SDraw/driver_kinectV2#3]
Is anything supposed yo happen when launching the kinect_calibrator.exe?

I can see the message about using the thumbsticks/touchpads and triggers inside VR, but nothing else is going on, no windows appear on my desktop, or anything else,

EDIT:

In fact, I've noticed that SteamVR seems to automatically remove the "activateMultipleDrivers" line from the config file upon launch.

**Comment by SDraw** [comment]
> Is anything supposed yo happen when launching the kinect_calibrator.exe?
> 
> I can see the message about using the thumbsticks/touchpads and triggers inside VR, but nothing else is going on, no windows appear on my desktop, or anything else,

Works as intended. If you see notification with input information, then calibrator is working. Console window only shows up if it's build in debug configuration.

> In fact, I've noticed that SteamVR seems to automatically remove the "activateMultipleDrivers" line from the config file upon launch.

That one I can't tell for sure, project doesn't use openvr settings interface from anywhere in code.

**Comment by Xonxt** [comment]
Yes, it just randomly started working. That's after ai moved the `activateMultipleDrivers` to the top of the config.

The tracking is a bit janky though... The hips and the ankles are fine, but the knees go crazy...

Still, a good project, and it's open source, unlike that Driver4VR, which didn't work that good for me either.
Thanks!
